- id: dclint
  name: DCLint
  description: Validate and enforce best practices in Docker Compose files.
  entry: dclint
  language: node
  language_version: 22.15.0
  additional_dependencies: [ "dclint@3.1.0" ]
  types: [ yaml ]
  files: '^(?:.*/)?(?:docker-)?compose\.ya?ml$'
- id: dclint-docker
  name: DCLint via Docker
  description: Validate and enforce best practices in Docker Compose files.
  language: docker_image
  entry: zavoloklom/dclint:3.1.0
  types: [ yaml ]
  files: '^(?:.*/)?(?:docker-)?compose\.ya?ml$'
